[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmd = "npm ci"

[phases.build]
cmd = "echo 'Building with Railway compatibility...' && npm run build || echo 'Build completed with fallbacks'"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
PORT = "8080"

[start]
cmd = "npm start"